In [ ]:
import pickle, os
import pandas as pd
from IPython.display import display

In [2]:
base_path = os.getcwd()
data_dir = os.path.join(base_path, "..", "data")

files = {
    'sentences': 'final_dataset_sentences.pickle',
    'sections':  'final_dataset_sections.pickle',
    'full':      'final_dataset.pickle'
}

datasets = {}
for key, filename in files.items():
    path = os.path.join(data_dir, filename)
    with open(path, 'rb') as f:
        datasets[key] = pickle.load(f)
        
final_dataset_sentences = datasets['sentences']
final_dataset_sections  = datasets['sections']
final_dataset           = datasets['full']

c:\Users\jimkos\Desktop\Portfolio\elcardiocc-baseline-ner\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
for sentence in final_dataset_sentences['train'][2]['sentences_tokens']:
    text = ''.join(sentence)
    print(text)
    print('..........')

ΕΝΗΜΕΡΩΤΙΚΟ ΣΗΜΕΙΩΜΑ
..........
Το ενημερωτικό σημείωμα να το έχετε μαζί σας κάθε φορά που θα επισκέπτεστε τον ιατρό
..........
ΙΣΤΟΡΙΚΟ – ΑΝΤΙΚΕΙΜΕΝΙΚΗ ΕΞΕΤΕΤΑΣΗ
Προσήλθε λόγω αναφερόμενης δύσπνοιας από 10ημέρου και κοιλιακής διδυμίας στο ΗΚΓ
Κλινική εξέταση: αν.ψιθ: κφ S1-S2: άρρυθμοι
ΑΠ: 140/70 mmHg SO2: 93% Σφύξεις: 100 bpm Θ: 36,6
..........
C
ΗΚΓ : SR, κοιλιακή διδυμία
Ατομικό Ιστορικό: ΑΥ, ΚΥΠ
..........
ΠΟΡΕΙΑ ΝΟΣΟΥ
Λόγω αυξημένης τιμής D-dimers έγινε CTPA που ανέδειξε πνευμονική εμβολή άμφω.
..........
Έγινε εισαγωγή στη Στεφανιαία Μονάδα όπου τέθηκε σε αντιπηκτική αγωγή παραμένοντας ασυμπτωματικός και αιμοδυναμικά σταθερός.
..........
Διενεργήθηκε triplex φλεβών κάτω άκρων που ανέδειξε θρόμβωση δεξιάς ιγνυακής, έγινε αγγειοχειρουργική εκτίμηση και εδόθησαν οδηγίες.
..........
Εξέρχεται ασυμπτωματικός με οδηγίες.
..........
ΔΙΑΓΝΩΣΗ ΕΞΟΔΟΥ
Πνευμονική εμβολή
..........
ΟΔΗΓΙΕΣ ΚΑΤΑ ΤΗΝ ΕΞΟΔΟ - ΠΑΡΑΤΗΡΗΣΕΙΣ
Επανέλεγχος από καρδιολόγο, πνευμονολόγο και ρευματολόγο σε τακτική βάση
Επανέλεγχος με υπερηχοκαρδιογράφημα την Δευτέρα xxx 9.30 πμ
Προγραμματισμός Holter ρυθμού σε τακτική βάση (τηλ. xxxxxxxxxx)
..........
Νέο Triplex φλεβών κάτω άκρων σε 6 μήνες και επανεκτίμηση από αγγειοχειρουργό
Χρήση κάλτσας ριζομηρίου κατ' οίκον
Επικοινωνία με το Μικροβιολογικό εργαστήριο του νοσοκομείου για λήψη των εργαστηριακών αποτελεσμάτων που εκκρεμούν
Τακτική λήψη της φαρμακευτικής αγωγής
..........
Δίαιτα υπολιπιδαιμική, πτωχή σε αλάτι
Αποφυγή αντιφλεγμονωδών φαρμάκων
ΦAΡΜΑΚΕΥΤΙΚΗ ΑΓΩΓΗ ΕΞΟΔΟΥ
Tb Xarelto 15 mg 1x2 έως xxx και tb Xarelto 20 mg 1x1 στη συνέχεια
Tb Carvepen 6,25 mg 1x2
Tb Duodart 0,4/0,6 mg 1x1
Tb Nexium 40 mg 1x1
Tb Lipitor 40 mg 1x1
..........
ΕΡΓΑΣΤΗΡΙΑΚΕΣ ΕΞΕΤΑΣΕΙΣ
..........
Επισυναπτονται
..........
ΕΞΕΤΑΣΕΙΣ
ΗΚΓ εξόδου
επισυνάπτεται
Υπερηχος Καρδιάς, Αξονική τομογραφία θώρακος, Triplex φλεβών κάτω άκρων
επισυνάπτεται
..........

In [9]:
pd.set_option('display.max_columns', None)
def visualize_patient_ner(dataset, subset, idx):
    patient_id = dataset[subset][idx]['patient_id']
    print(f"Patient ID: {patient_id} (Index: {idx})")
    for i in range(len(dataset[subset][idx]['sentences_tokens'])):
        sentence = pd.DataFrame([dataset['train'][idx]['sentences_tokens'][i], dataset[subset][idx]['sentences_ner_tags'][i]],index=["tokens", "ner_tags"])
        display(sentence)

visualize_patient_ner(final_dataset_sentences, 'train', 4) #4th record of trainset

Patient ID: 23 (Index: 4)

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19
tokens    Ε  Ν  Η  Μ  Ε  Ρ  Ω  Τ  Ι  Κ  Ο     Σ  Η  Μ  Ε  Ι  Ω  Μ  Α
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
tokens    Τ  ο     ε  ν  η  μ  ε  ρ  ω  τ  ι  κ  ό     σ  η  μ  ε  ί  ω  μ  α     ν  α     τ  ο     έ  χ  ε  τ  ε     μ  α  ζ  ί     σ  α  ς     κ  ά  θ  ε     φ  ο  ρ  ά     π  ο  υ     θ  α     ε  π  ι  σ  κ  έ  π  τ  ε  σ  τ  ε     τ  ο  ν     ι  α  τ  ρ  ό
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
tokens     Α   Ι   Τ   Ι   Α       Ε   Ι   Σ   Ο   Δ   Ο   Υ       –       Α   Ν   Τ   Ι   Κ   Ε   Ι   Μ   Ε   Ν   Ι   Κ   Η       Ε   Ξ   Ε   Τ   Ε   Τ   Α   Σ   Η       -       Ι   Σ   Τ   Ο   Ρ   Ι   Κ   Ο  \n   Α   ι   τ   ί   α       ε   ι   σ   ό   δ   ο   υ   :       λ   ι   π   ο   θ   υ   μ   ι   κ   ό       ε   π   ε   ι   σ   ό   δ   ι   ο       χ   ω   ρ   ί   ς       π   ρ   ό   δ   ρ   ο   μ   α       σ   υ   μ   π   τ   ώ   μ   α   τ   α   ,       θ   λ   α   σ   τ   ι   κ   ό       τ   ρ   α   ύ   μ   α       σ   τ   ο       φ   ρ   ύ   δ   ι       δ   ε   ξ   ι   ά   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   1   1   1   1   1   1   2   2   2   2   2   2   2   2   2   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
tokens     Κ   λ   ι   ν   ι   κ   ή       Ε   ξ   έ   τ   α   σ   η   :       Α   Π   :       1   6   5   /   1   1   5   m   m       H   g   ,       S   p   O   2   :       9   7       %   ,       (   F   i   O   2   =   2   1   %   )   ,       σ   φ   :       7   5   /   m   i   n       S   1   -   S   2   :       ε   υ   κ   ρ   ι   ν   ε   ί   ς  \n   Α   τ   ο   μ   ι   κ   ό       Ι   σ   τ   ο   ρ   ι   κ   ό   :       Σ   τ   ε   φ   α   ν   ι   α   ί   α       Ν   ό   σ   ο   ς   -       Ο   Ε   Μ       τ   ο       2   0   1   1   -       p   c   i       σ   τ   ο   ν       L   A   D   ,       ε   μ   φ   ύ   τ   ε   υ   σ   η       I   C   D       (   x   x   x   )   ,       s   t   e   n   t       λ   α   γ   ο   ν   ί   ω   ν   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   1   1   1   1   1   1   2   2   2   2   2   2   0   0   1   1   1   0   0   0   0   0   0   0   0   0   0   1   1   1   2   2   2   2   2   2   2   2   2   0   0   1   1   1   1   1   1   1   1   1   2   2   2   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25  26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
tokens    Η  Κ  Γ     ε  ι  σ  α  γ  ω  γ  ή  ς  :     S  R  ,     Q     V  2  -  V  3  \n  Α  κ  τ  ι  ν  ο  γ  ρ  α  φ  ί  α     Θ  ώ  ρ  α  κ  ο  ς     Ε  ι  σ  α  γ  ω  γ  ή  ς  :
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94
tokens    Α  ν  ύ  ψ  ω  σ  η     τ  ο  υ     α  ρ     η  μ  ι  δ  ι  α  φ  ρ  ά  γ  μ  α  τ  ο  ς     μ  ε     π  α  ρ  ο  υ  σ  ί  α     α  ε  ρ  ο  π  λ  η  θ  ο  ύ  ς     ε  ν  τ  ε  ρ  ι  κ  ή  ς     έ  λ  ι  κ  α  ς  -  σ  τ  ο  μ  ά  χ  ο  υ     κ  ά  τ  ω  θ  ε  ν     α  υ  τ  ο  ύ  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
tokens    Τ  ο     α  π  ε  ι  κ  ο  ν  ι  ζ  ό  μ  ε  ν  ο     π  ν  ε  υ  μ  ο  ν  ι  κ  ό     π  α  ρ  έ  γ  χ  υ  μ  α     δ  ι  α  υ  γ  ά  ζ  ε  ι     κ  α  λ  ώ  ς  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11
tokens    Π  Ο  Ρ  Ε  Ι  Α     Ν  Ο  Σ  Ο  Υ
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142
tokens     Ο       α   σ   θ   ε   ν   ή   ς       π   ρ   ο   σ   ή   λ   θ   ε       λ   ό   γ   ω       λ   ι   π   ο   θ   υ   μ   ι   κ   ο   ύ       ε   π   ε   ι   σ   ο   δ   ί   ο   υ   ,       χ   ω   ρ   ί   ς       π   ρ   ό   δ   ρ   ο   μ   α       σ   υ   μ   π   τ   ώ   μ   α   τ   α       κ   α   ι       κ   ά   κ   ω   σ   η       κ   ε   φ   α   λ   ή   ς       μ   ε       θ   λ   α   σ   τ   ι   κ   ό       τ   ρ   α   ύ   μ   α       σ   τ   ο       φ   ρ   ύ   δ   ι       δ   ε   ξ   ι   ά       κ   α   ι       σ   τ   ο       μ   έ   τ   ω   π   ο   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   1   1   1   1   1   1   1   2   2   2   2   2   2   2   2   2   2   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
tokens    Α  ν  έ  φ  ε  ρ  ε     ό  τ  ι     ε  ί  χ  ε     π  ρ  ο  η  γ  η  θ  ε  ί     κ  α  τ  α  ν  ά  λ  ω  σ  η     α  λ  κ  ο  ό  λ  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
tokens    Ο     Α  σ  θ  ε  ν  ή  ς     δ  ε  ν     α  ν  έ  φ  ε  ρ  ε     ό  τ  ι     έ  γ  ι  ν  ε     ε  κ  φ  ό  ρ  τ  ι  σ  η     α  π  ι  ν  ι  δ  ω  τ  ή  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  0

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
tokens     Σ   τ   ο       Τ   Ε   Π       ε   κ   τ   ι   μ   ή   θ   η   κ   ε       α   π   ό       Ν   Ρ   Χ   ,       δ   ι   ε   ν   ε   ρ   γ   ή   θ   η   κ   ε       C   T       ε   γ   κ   ε   φ   ά   λ   ο   υ   ,       δ   ε   ν       π   ρ   ο   έ   κ   υ   ψ   ε       κ   ά   τ   ι       ο   ξ   ύ       ν   ε   υ   ρ   ο   χ   ε   ι   ρ   ο   υ   ρ   γ   ι   κ   ό       κ   α   ι       έ   γ   ι   ν   ε       σ   υ   ρ   ρ   α   φ   ή       τ   ο   υ       θ   λ   α   σ   τ   ι   κ   ο   ύ       τ   ρ   α   ύ   μ   α   τ   ο   ς   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41
tokens    Ή  τ  α  ν     α  σ  υ  μ  π  τ  ω  μ  α  τ  ι  κ  ό  ς     κ  α  τ  ά     τ  η  ν     ν  ο  σ  η  λ  ε  ί  α     τ  ο  υ  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
tokens    Π  α  ρ  α  τ  η  ρ  ή  θ  η  κ  α  ν     υ  ψ  η  λ  έ  ς     τ  ι  μ  έ  ς     α  ρ  τ  η  ρ  ι  α  κ  ή  ς     π  ί  ε  σ  η  ς     κ  α  ι     τ  ρ  ο  π  ο  π  ο  ι  ή  θ  η  κ  ε     η     φ  α  ρ  μ  α  κ  ε  υ  τ  ι  κ  ή     τ  ο  υ     α  γ  ω  γ  ή  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
tokens    Δ  ε  ν     π  α  ρ  ο  υ  σ  ί  α  σ  ε     α  ύ  ξ  η  σ  η     μ  υ  ο  κ  α  ρ  δ  ι  α  κ  ώ  ν     ε  ν  ζ  ύ  μ  ω  ν  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
tokens     Έ   γ   ι   ν   ε       ε   κ   τ   ί   μ   η   σ   η       τ   ο   υ       α   π   ι   ν   ι   δ   ω   τ   ή       α   π   ό       τ   ε   χ   ν   ι   κ   ό       τ   η   ς       ε   τ   α   ι   ρ   ε   ί   α   ς       τ   ο   υ       α   π   ι   ν   ι   δ   ω   τ   ή   ,       δ   ε   ν       α   ν   α   φ   έ   ρ   θ   η   κ   ε       κ   ά   π   ο   ι   α       α   ρ   ρ   υ   θ   μ   ί   α       ή       δ   ι   α   τ   α   ρ   α   χ   ή       τ   η   ς       κ   ο   λ   π   ο   κ   ο   ι   λ   ι   α   κ   ή   ς       α   γ   ω   γ   ή   ς   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   1   1   1   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
tokens    Λ  ό  γ  ω     α  π  ώ  λ  ε  ι  α     μ  ν  ή  μ  η  ς     σ  χ  ε  τ  ι  κ  ά     μ  ε     τ  ο     σ  υ  μ  β  ά  ν  ,     ζ  η  τ  ή  θ  η  κ  ε     Ν  Ρ  Λ     ε  κ  τ  ί  μ  η  σ  η  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22
tokens    Ε  Ρ  Γ  Α  Σ  Τ  Η  Ρ  Ι  Α  Κ  Ε  Σ     Ε  Ξ  Ε  Τ  Α  Σ  Ε  Ι  Σ
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
tokens     Ε   Ρ   Γ   Α   Σ   Τ   Η   Ρ   Ι   Α   Κ   Ε   Σ       Ε   Ξ   Ε   Τ   Α   Σ   Ε   Ι   Σ       Ε   Π   Ι   Σ   Υ   Ν   Α   Π   Τ   Ο   Ν   Τ   Α   Ι  \n   W   B   C  \n   G   l   u   c   o   s   e  \n   γ   -   G   T  \n   F   e  \n   N   E   U   T  \n   U   R   E   A  \n   A   L   P  \n   L   Y   M   P   H  \n   C   R   E   A   T  \n   C   P   K  \n   T   o   t   .       P   r   o   t   .  \n   H   C   T  \n   K  \n   C   P   K   -   M   B  \n   A   L   B  \n   H   b  \n   N   a  \n   L   D   H  \n   G   l   o   b   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0  1  2   3  4  5  6  7   8  9  10 11 12  13 14 15 16  17 18 19 20  21 22 23 24 25  26 27 28 29 30 31  32 33 34 35  36 37 38 39  40 41 42 43 44 45  46 47 48 49  50 51 52 53 54 55 56 57 58  59 60 61 62 63 64  65 66 67 68  69 70 71 72 73 74 75 76 77
tokens    P  L  T  \n  S  G  O  T  \n  C  H  O  L  \n  T  S  H  \n  T  K  E  \n  S  G  P  T  \n  T  R  I  G  L  \n  f  T  4  \n  I  N  R  \n  B  I  L  -  T  \n  H  D  L  \n  D  -  D  i  m  e  r  s  \n  B  I  L  -  D  \n  L  D  L  \n  T  r  o  p  o  n  i  n
ner_tags  0  0  0   0  0  0  0  0   0  0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0  0   0  0  0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0  0  0   0  0  0  0   0  0  0  0  0  0  0  0  0   0  0  0  0  0  0   0  0  0  0   0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21  22 23 24 25 26 27 28 29 30 31 32 33  34 35 36 37 38 39 40 41 42 43 44 45
tokens    Π  Α  Ρ  Α  Κ  Λ  Ι  Ν  Ι  Κ  Ε  Σ     Ε  Ξ  Ε  Τ  Α  Σ  Ε  Ι  Σ  \n  Η  Κ  Γ     ε  ξ  ό  δ  ο  υ  :  \n  S  R  ,     Q     v  2  -  v  3
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0   0  0  0  0  0  0  0  0  0  0  0  0   0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
tokens    Λ  ο  ι  π  έ  ς     ε  ξ  ε  τ  ά  σ  ε  ι  ς  :
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
tokens    Α  ξ  ο  ν  ι  κ  ή     τ  ο  μ  ο  γ  ρ  α  φ  ί  α     ε  γ  κ  ε  φ  ά  λ  ο  υ  :  ε  π  ι  σ  υ  ν  ά  π  τ  ε  τ  α  ι  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84
tokens    U  /  S     κ  α  ρ  δ  ι  ά  ς  :     α  κ  ι  ν  η  σ  ί  α     μ  ε     α  ν  ε  υ  ρ  υ  σ  μ  α  τ  ο  ε  ι  δ  ή     δ  ι  ά  τ  α  σ  η     τ  η  ς     κ  ο  ρ  υ  φ  ή  ς     (  χ  ω  ρ  ί  ς     π  α  ρ  ο  υ  σ  ί  α     θ  ρ  ό  μ  β  ο  υ  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
tokens    A  R     1  +  /  4  +  ,     T  R     1  +  /  4  +  ,     E  <  A  .     π  ε  ρ  ι  κ  ά  ρ  δ  ι  ο     ε  λ  ε  ύ  θ  ε  ρ  ο  .
ner_tags  1  1  2  2  2  2  2  2  0  0  1  1  2  2  2  2  2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14  15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
tokens    Δ  Ι  Α  Γ  Ν  Ω  Σ  Η     Ε  Ξ  Ο  Δ  Ο  Υ  \n  Λ  ι  π  ο  θ  υ  μ  ι  κ  ό     ε  π  ε  ι  σ  ό  δ  ι  ο
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0   0  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2

         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100 101 102 103 104 105 106 107 108 109
tokens     Ο   Δ   Η   Γ   Ι   Ε   Σ       Κ   Α   Τ   Α       Τ   Η   Ν       Ε   Ξ   Ο   Δ   Ο       -       Π   Α   Ρ   Α   Τ   Η   Ρ   Η   Σ   Ε   Ι   Σ  \n   Τ   α   κ   τ   ι   κ   ή       κ   α   ρ   δ   ι   ο   λ   ο   γ   ι   κ   ή       π   α   ρ   α   κ   ο   λ   ο   ύ   θ   η   σ   η       -       Ε   π   ι   μ   ε   λ   ή   ς       λ   ή   ψ   η       φ   α   ρ   μ   α   κ   ε   υ   τ   ι   κ   ή   ς       α   γ   ω   γ   ή   ς   .
ner_tags   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

         0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
tokens    Α  π  ο  φ  υ  γ  ή     κ  α  τ  α  ν  ά  λ  ω  σ  η  ς     α  λ  κ  ο  ό  λ  .
ner_tags  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291
tokens,Φ,α,ρ,μ,.,,Α,γ,ω,γ,ή,,(,ε,ξ,ό,δ,ο,υ,),,:,,1,),,a,n,g,o,r,o,n,,2,0,0,m,g,,s,:,1,x,1,\n,3,),P,l,a,v,i,x,,7,5,m,g,,s,:,1,x,1,\n,5,),,l,a,s,i,x,,4,0,,m,g,,s,:,1,x,1,\n,7,),e,n,t,a,c,t,,2,0,,m,g,,s,:,1,x,1,\n,9,),i,n,o,s,a,m,i,n,,2,5,,m,g,,s,:,1,x,1,\n,1,1,),L,i,p,i,t,o,r,,4,0,,m,g,,s,:,1,x,1,\n,2,),,t,r,i,a,t,e,c,,5,m,g,,s,:,1,x,2,\n,4,),c,a,r,v,e,p,e,n,,6,.,2,5,,s,:,1,x,2,\n,6,),z,u,r,c,a,z,o,l,,4,0,,m,g,,s,:,1,x,1,\n,8,),,c,e,n,t,r,a,c,,1,0,,m,g,,s,:,1,/,2,,x,2,\n,1,0,),,z,y,l,o,r,i,c,,1,0,0,,m,g,,s,:,1,x,1,\n,1,2,),,n,o,r,v,a,s,c,,5,m,g,,s,:,1,x,1
ner_tags,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [18]:
for i in range(len(final_dataset['train'])):
  if final_dataset['train'][i]['patient_id'] != final_dataset_sentences['train'][i]['patient_id']:
    print('the patient ids are mixed')
    break

In [17]:
document_stats = {}

for split, instances in final_dataset_sentences.items():
    max_sentences = max(len(instance['sentences_tokens']) for instance in instances)
    min_sentences = min(len(instance['sentences_tokens']) for instance in instances)
    avg_sentences = sum(len(instance['sentences_tokens']) for instance in instances) / len(instances)

    document_stats[split] = {
        'max_sentences': max_sentences,
        'min_sentences': min_sentences,
        'avg_sentences': avg_sentences,
        'num_instances': len(instances),
        'total_sentences': sum(len(instance['sentences_tokens']) for instance in instances)
    }

for split, stats in document_stats.items():
    print(f"{split} Split:")
    print(f"   Max Sentences: {stats['max_sentences']}")
    print(f"   Min Sentences: {stats['min_sentences']}")
    print(f"   Avg Sentences: {stats['avg_sentences']}")
    print(f"   Number of Instances: {stats['num_instances']}")
    print(f"   Total Sentences: {stats['total_sentences']}")
    print()

train Split:
   Max Sentences: 72
   Min Sentences: 11
   Avg Sentences: 25.43625
   Number of Instances: 800
   Total Sentences: 20349

validation Split:
   Max Sentences: 55
   Min Sentences: 13
   Avg Sentences: 25.555
   Number of Instances: 200
   Total Sentences: 5111